# Generated by Django 4.0.2 on 2022-04-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packageAndRooms', '0002_package_no_days_package_number_of_people_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
