# Generated by Django 4.0.2 on 2022-04-14 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packageAndRooms', '0003_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='User',
        ),
    ]
